version: 2

python:
  install:
    - path: .
      extra_requirements:
        - docs
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      ## TODO: unbuntu-22.04 does not ship cmake 3.25
      #- cmake --workflow --preset rtd
      - cmake -THINGFRAMEWORK_DOCS=ON -THINGFRAMEWORK_TEST=OFF -B ./cmake-build-docs
      - cmake --build ./cmake-build-docs --target ThingsFramework_doxygen
sphinx:
  configuration: doc/conf.py
