name: test
run-name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  ctest:
    runs-on: ubuntu-latest
    container: ghcr.io/lecrisut/dev-env:latest
    strategy:
      matrix:
        # Only llvm is currently supported
#        toolchain: [ gcc, intel, llvm ]
        toolchain: [ llvm ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # workaround for https://github.com/actions/runner/issues/2033
      - name: ownership workaround
        run: git config --system --add safe.directory '*'
      - name: Activate Intel compilers
        # Not elegant, it will propagate all environment variable.
        # Intel does not provide a way to output the environment variables to a file
        # Note: PATH needs to be exported to GITHUB_PATH otherwise it can be overwritten
        run: |
          source /opt/intel/oneapi/setvars.sh
          printenv >> $GITHUB_ENV
          echo $PATH >> $GITHUB_PATH
        if: matrix.toolchain == 'intel'

      ## Main
      - name: Run CMake configuration for ${{ matrix.toolchain }} toolchain
        uses: lukka/run-cmake@v10.3
        with:
          workflowPreset: "${{ matrix.toolchain }}-ci"

  coverage:
    runs-on: ubuntu-latest
    needs: [ ctest ]
    container: ghcr.io/lecrisut/dev-env:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # workaround for https://github.com/actions/runner/issues/2033
      - name: ownership workaround
        run: git config --system --add safe.directory '*'
      - name: Get test coverage
        uses: lukka/run-cmake@v10.3
        with:
          workflowPreset: ci-coverage
      - name: Get llvm-cov data
        run: |
          llvm-profdata merge -sparse $(find ./cmake-build-coverage -name *.profraw) -o coverage.profdata
          llvm-cov export ./cmake-build-coverage/libThingFramework.so -instr-profile=./coverage.profdata --format lcov > coverage.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: Test coverage
          files: coverage.info
          verbose: true
